/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Campaign {
  'id' : Id,
  'status' : CampaignStatus,
  'startedAt' : [] | [Timestamp],
  'delaySecs' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'totalCount' : bigint,
  'sentCount' : bigint,
  'messageType' : MessageType,
  'message' : string,
  'mediaPath' : [] | [string],
  'clientIds' : Array<string>,
  'listId' : Id,
  'scheduledAt' : [] | [Timestamp],
}
export interface CampaignRequest {
  'delaySecs' : bigint,
  'name' : string,
  'messageType' : MessageType,
  'message' : string,
  'mediaPath' : [] | [string],
  'clientIds' : Array<string>,
  'listId' : Id,
  'scheduledAt' : [] | [Timestamp],
}
export type CampaignStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'running' : null } |
  { 'paused' : null };
export interface ClientStatus {
  'clientId' : string,
  'lastSeenAt' : [] | [Timestamp],
  'name' : string,
  'connected' : boolean,
  'phone' : [] | [string],
}
export interface Contact {
  'id' : Id,
  'name' : string,
  'createdAt' : Timestamp,
  'phone' : string,
  'listId' : Id,
}
export interface ContactInput { 'name' : string, 'phone' : string }
export interface ContactList {
  'id' : Id,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
}
export interface DashboardStats {
  'connectedClients' : bigint,
  'runningCampaigns' : bigint,
  'totalClients' : bigint,
  'totalCampaigns' : bigint,
  'totalContactLists' : bigint,
}
export interface GroupContact {
  'name' : string,
  'isAdmin' : boolean,
  'phone' : string,
}
export type Id = bigint;
export interface MessageFilter {
  'status' : [] | [MessageStatus],
  'campaignId' : [] | [Id],
  'toTime' : [] | [Timestamp],
  'fromTime' : [] | [Timestamp],
}
export interface MessageLog {
  'id' : Id,
  'status' : MessageStatus,
  'messagePreview' : string,
  'campaignId' : Id,
  'sentAt' : Timestamp,
  'error' : [] | [string],
  'contactId' : Id,
  'phone' : string,
}
export interface MessageLogInput {
  'status' : MessageStatus,
  'messagePreview' : string,
  'campaignId' : Id,
  'error' : [] | [string],
  'contactId' : Id,
  'phone' : string,
}
export type MessageStatus = { 'sent' : null } |
  { 'failed' : null };
export type MessageType = { 'imageText' : null } |
  { 'text' : null } |
  { 'videoText' : null } |
  { 'document' : null };
export type Timestamp = bigint;
export interface _SERVICE {
  'addContact' : ActorMethod<[Id, string, string], Id>,
  'addMessageLog' : ActorMethod<[MessageLogInput], Id>,
  'connectClient' : ActorMethod<[string], boolean>,
  'createCampaign' : ActorMethod<[CampaignRequest], Id>,
  'createContactList' : ActorMethod<[string, string], Id>,
  'deleteCampaign' : ActorMethod<[Id], boolean>,
  'deleteContact' : ActorMethod<[Id], boolean>,
  'deleteContactList' : ActorMethod<[Id], boolean>,
  'disconnectClient' : ActorMethod<[string], boolean>,
  'extractGroupContacts' : ActorMethod<[string, string], Array<GroupContact>>,
  'getCampaigns' : ActorMethod<[], Array<Campaign>>,
  'getClientStatuses' : ActorMethod<[], Array<ClientStatus>>,
  'getContactLists' : ActorMethod<[], Array<ContactList>>,
  'getContactsInList' : ActorMethod<[Id], Array<Contact>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getMessageLogs' : ActorMethod<[MessageFilter], Array<MessageLog>>,
  'importContacts' : ActorMethod<[Id, Array<ContactInput>], bigint>,
  'pauseCampaign' : ActorMethod<[Id], boolean>,
  'saveGroupContactsToList' : ActorMethod<[Id, Array<ContactInput>], bigint>,
  'startCampaign' : ActorMethod<[Id], boolean>,
  'updateClientStatus' : ActorMethod<[string, boolean, [] | [string]], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];