/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Id = IDL.Nat;
export const MessageStatus = IDL.Variant({
  'sent' : IDL.Null,
  'failed' : IDL.Null,
});
export const MessageLogInput = IDL.Record({
  'status' : MessageStatus,
  'messagePreview' : IDL.Text,
  'campaignId' : Id,
  'error' : IDL.Opt(IDL.Text),
  'contactId' : Id,
  'phone' : IDL.Text,
});
export const MessageType = IDL.Variant({
  'imageText' : IDL.Null,
  'text' : IDL.Null,
  'videoText' : IDL.Null,
  'document' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const CampaignRequest = IDL.Record({
  'delaySecs' : IDL.Nat,
  'name' : IDL.Text,
  'messageType' : MessageType,
  'message' : IDL.Text,
  'mediaPath' : IDL.Opt(IDL.Text),
  'clientIds' : IDL.Vec(IDL.Text),
  'listId' : Id,
  'scheduledAt' : IDL.Opt(Timestamp),
});
export const GroupContact = IDL.Record({
  'name' : IDL.Text,
  'isAdmin' : IDL.Bool,
  'phone' : IDL.Text,
});
export const CampaignStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'running' : IDL.Null,
  'paused' : IDL.Null,
});
export const Campaign = IDL.Record({
  'id' : Id,
  'status' : CampaignStatus,
  'startedAt' : IDL.Opt(Timestamp),
  'delaySecs' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'totalCount' : IDL.Nat,
  'sentCount' : IDL.Nat,
  'messageType' : MessageType,
  'message' : IDL.Text,
  'mediaPath' : IDL.Opt(IDL.Text),
  'clientIds' : IDL.Vec(IDL.Text),
  'listId' : Id,
  'scheduledAt' : IDL.Opt(Timestamp),
});
export const ClientStatus = IDL.Record({
  'clientId' : IDL.Text,
  'lastSeenAt' : IDL.Opt(Timestamp),
  'name' : IDL.Text,
  'connected' : IDL.Bool,
  'phone' : IDL.Opt(IDL.Text),
});
export const ContactList = IDL.Record({
  'id' : Id,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
});
export const Contact = IDL.Record({
  'id' : Id,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'phone' : IDL.Text,
  'listId' : Id,
});
export const DashboardStats = IDL.Record({
  'connectedClients' : IDL.Nat,
  'runningCampaigns' : IDL.Nat,
  'totalClients' : IDL.Nat,
  'totalCampaigns' : IDL.Nat,
  'totalContactLists' : IDL.Nat,
});
export const MessageFilter = IDL.Record({
  'status' : IDL.Opt(MessageStatus),
  'campaignId' : IDL.Opt(Id),
  'toTime' : IDL.Opt(Timestamp),
  'fromTime' : IDL.Opt(Timestamp),
});
export const MessageLog = IDL.Record({
  'id' : Id,
  'status' : MessageStatus,
  'messagePreview' : IDL.Text,
  'campaignId' : Id,
  'sentAt' : Timestamp,
  'error' : IDL.Opt(IDL.Text),
  'contactId' : Id,
  'phone' : IDL.Text,
});
export const ContactInput = IDL.Record({
  'name' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addContact' : IDL.Func([Id, IDL.Text, IDL.Text], [Id], []),
  'addMessageLog' : IDL.Func([MessageLogInput], [Id], []),
  'connectClient' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'createCampaign' : IDL.Func([CampaignRequest], [Id], []),
  'createContactList' : IDL.Func([IDL.Text, IDL.Text], [Id], []),
  'deleteCampaign' : IDL.Func([Id], [IDL.Bool], []),
  'deleteContact' : IDL.Func([Id], [IDL.Bool], []),
  'deleteContactList' : IDL.Func([Id], [IDL.Bool], []),
  'disconnectClient' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'extractGroupContacts' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(GroupContact)],
      [],
    ),
  'getCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
  'getClientStatuses' : IDL.Func([], [IDL.Vec(ClientStatus)], ['query']),
  'getContactLists' : IDL.Func([], [IDL.Vec(ContactList)], ['query']),
  'getContactsInList' : IDL.Func([Id], [IDL.Vec(Contact)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getMessageLogs' : IDL.Func(
      [MessageFilter],
      [IDL.Vec(MessageLog)],
      ['query'],
    ),
  'importContacts' : IDL.Func([Id, IDL.Vec(ContactInput)], [IDL.Nat], []),
  'pauseCampaign' : IDL.Func([Id], [IDL.Bool], []),
  'saveGroupContactsToList' : IDL.Func(
      [Id, IDL.Vec(ContactInput)],
      [IDL.Nat],
      [],
    ),
  'startCampaign' : IDL.Func([Id], [IDL.Bool], []),
  'updateClientStatus' : IDL.Func(
      [IDL.Text, IDL.Bool, IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Id = IDL.Nat;
  const MessageStatus = IDL.Variant({ 'sent' : IDL.Null, 'failed' : IDL.Null });
  const MessageLogInput = IDL.Record({
    'status' : MessageStatus,
    'messagePreview' : IDL.Text,
    'campaignId' : Id,
    'error' : IDL.Opt(IDL.Text),
    'contactId' : Id,
    'phone' : IDL.Text,
  });
  const MessageType = IDL.Variant({
    'imageText' : IDL.Null,
    'text' : IDL.Null,
    'videoText' : IDL.Null,
    'document' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const CampaignRequest = IDL.Record({
    'delaySecs' : IDL.Nat,
    'name' : IDL.Text,
    'messageType' : MessageType,
    'message' : IDL.Text,
    'mediaPath' : IDL.Opt(IDL.Text),
    'clientIds' : IDL.Vec(IDL.Text),
    'listId' : Id,
    'scheduledAt' : IDL.Opt(Timestamp),
  });
  const GroupContact = IDL.Record({
    'name' : IDL.Text,
    'isAdmin' : IDL.Bool,
    'phone' : IDL.Text,
  });
  const CampaignStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'running' : IDL.Null,
    'paused' : IDL.Null,
  });
  const Campaign = IDL.Record({
    'id' : Id,
    'status' : CampaignStatus,
    'startedAt' : IDL.Opt(Timestamp),
    'delaySecs' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'totalCount' : IDL.Nat,
    'sentCount' : IDL.Nat,
    'messageType' : MessageType,
    'message' : IDL.Text,
    'mediaPath' : IDL.Opt(IDL.Text),
    'clientIds' : IDL.Vec(IDL.Text),
    'listId' : Id,
    'scheduledAt' : IDL.Opt(Timestamp),
  });
  const ClientStatus = IDL.Record({
    'clientId' : IDL.Text,
    'lastSeenAt' : IDL.Opt(Timestamp),
    'name' : IDL.Text,
    'connected' : IDL.Bool,
    'phone' : IDL.Opt(IDL.Text),
  });
  const ContactList = IDL.Record({
    'id' : Id,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
  });
  const Contact = IDL.Record({
    'id' : Id,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'phone' : IDL.Text,
    'listId' : Id,
  });
  const DashboardStats = IDL.Record({
    'connectedClients' : IDL.Nat,
    'runningCampaigns' : IDL.Nat,
    'totalClients' : IDL.Nat,
    'totalCampaigns' : IDL.Nat,
    'totalContactLists' : IDL.Nat,
  });
  const MessageFilter = IDL.Record({
    'status' : IDL.Opt(MessageStatus),
    'campaignId' : IDL.Opt(Id),
    'toTime' : IDL.Opt(Timestamp),
    'fromTime' : IDL.Opt(Timestamp),
  });
  const MessageLog = IDL.Record({
    'id' : Id,
    'status' : MessageStatus,
    'messagePreview' : IDL.Text,
    'campaignId' : Id,
    'sentAt' : Timestamp,
    'error' : IDL.Opt(IDL.Text),
    'contactId' : Id,
    'phone' : IDL.Text,
  });
  const ContactInput = IDL.Record({ 'name' : IDL.Text, 'phone' : IDL.Text });
  
  return IDL.Service({
    'addContact' : IDL.Func([Id, IDL.Text, IDL.Text], [Id], []),
    'addMessageLog' : IDL.Func([MessageLogInput], [Id], []),
    'connectClient' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'createCampaign' : IDL.Func([CampaignRequest], [Id], []),
    'createContactList' : IDL.Func([IDL.Text, IDL.Text], [Id], []),
    'deleteCampaign' : IDL.Func([Id], [IDL.Bool], []),
    'deleteContact' : IDL.Func([Id], [IDL.Bool], []),
    'deleteContactList' : IDL.Func([Id], [IDL.Bool], []),
    'disconnectClient' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'extractGroupContacts' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(GroupContact)],
        [],
      ),
    'getCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
    'getClientStatuses' : IDL.Func([], [IDL.Vec(ClientStatus)], ['query']),
    'getContactLists' : IDL.Func([], [IDL.Vec(ContactList)], ['query']),
    'getContactsInList' : IDL.Func([Id], [IDL.Vec(Contact)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getMessageLogs' : IDL.Func(
        [MessageFilter],
        [IDL.Vec(MessageLog)],
        ['query'],
      ),
    'importContacts' : IDL.Func([Id, IDL.Vec(ContactInput)], [IDL.Nat], []),
    'pauseCampaign' : IDL.Func([Id], [IDL.Bool], []),
    'saveGroupContactsToList' : IDL.Func(
        [Id, IDL.Vec(ContactInput)],
        [IDL.Nat],
        [],
      ),
    'startCampaign' : IDL.Func([Id], [IDL.Bool], []),
    'updateClientStatus' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };