/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ContactInput {
    name: string;
    phone: string;
}
export type Timestamp = bigint;
export interface Contact {
    id: Id;
    name: string;
    createdAt: Timestamp;
    phone: string;
    listId: Id;
}
export interface MessageLog {
    id: Id;
    status: MessageStatus;
    messagePreview: string;
    campaignId: Id;
    sentAt: Timestamp;
    error?: string;
    contactId: Id;
    phone: string;
}
export interface MessageLogInput {
    status: MessageStatus;
    messagePreview: string;
    campaignId: Id;
    error?: string;
    contactId: Id;
    phone: string;
}
export interface DashboardStats {
    connectedClients: bigint;
    runningCampaigns: bigint;
    totalClients: bigint;
    totalCampaigns: bigint;
    totalContactLists: bigint;
}
export interface GroupContact {
    name: string;
    isAdmin: boolean;
    phone: string;
}
export interface ContactList {
    id: Id;
    name: string;
    createdAt: Timestamp;
    description: string;
}
export interface CampaignRequest {
    delaySecs: bigint;
    name: string;
    messageType: MessageType;
    message: string;
    mediaPath?: string;
    clientIds: Array<string>;
    listId: Id;
    scheduledAt?: Timestamp;
}
export interface Campaign {
    id: Id;
    status: CampaignStatus;
    startedAt?: Timestamp;
    delaySecs: bigint;
    name: string;
    createdAt: Timestamp;
    totalCount: bigint;
    sentCount: bigint;
    messageType: MessageType;
    message: string;
    mediaPath?: string;
    clientIds: Array<string>;
    listId: Id;
    scheduledAt?: Timestamp;
}
export type Id = bigint;
export interface MessageFilter {
    status?: MessageStatus;
    campaignId?: Id;
    toTime?: Timestamp;
    fromTime?: Timestamp;
}
export interface ClientStatus {
    clientId: string;
    lastSeenAt?: Timestamp;
    name: string;
    connected: boolean;
    phone?: string;
}
export enum CampaignStatus {
    pending = "pending",
    completed = "completed",
    running = "running",
    paused = "paused"
}
export enum MessageStatus {
    sent = "sent",
    failed = "failed"
}
export enum MessageType {
    imageText = "imageText",
    text = "text",
    videoText = "videoText",
    document_ = "document"
}
export interface backendInterface {
    addContact(listId: Id, name: string, phone: string): Promise<Id>;
    addMessageLog(log: MessageLogInput): Promise<Id>;
    connectClient(clientId: string): Promise<boolean>;
    createCampaign(req: CampaignRequest): Promise<Id>;
    createContactList(name: string, description: string): Promise<Id>;
    deleteCampaign(id: Id): Promise<boolean>;
    deleteContact(id: Id): Promise<boolean>;
    deleteContactList(id: Id): Promise<boolean>;
    disconnectClient(clientId: string): Promise<boolean>;
    extractGroupContacts(groupId: string, clientId: string): Promise<Array<GroupContact>>;
    getCampaigns(): Promise<Array<Campaign>>;
    getClientStatuses(): Promise<Array<ClientStatus>>;
    getContactLists(): Promise<Array<ContactList>>;
    getContactsInList(listId: Id): Promise<Array<Contact>>;
    getDashboardStats(): Promise<DashboardStats>;
    getMessageLogs(filter: MessageFilter): Promise<Array<MessageLog>>;
    importContacts(listId: Id, contacts: Array<ContactInput>): Promise<bigint>;
    pauseCampaign(id: Id): Promise<boolean>;
    saveGroupContactsToList(listId: Id, contacts: Array<ContactInput>): Promise<bigint>;
    startCampaign(id: Id): Promise<boolean>;
    updateClientStatus(clientId: string, connected: boolean, phone: string | null): Promise<boolean>;
}
import type { Campaign as _Campaign, CampaignRequest as _CampaignRequest, CampaignStatus as _CampaignStatus, ClientStatus as _ClientStatus, Id as _Id, MessageFilter as _MessageFilter, MessageLog as _MessageLog, MessageLogInput as _MessageLogInput, MessageStatus as _MessageStatus, MessageType as _MessageType, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addContact(arg0: Id, arg1: string, arg2: string): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.addContact(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addContact(arg0, arg1, arg2);
            return result;
        }
    }
    async addMessageLog(arg0: MessageLogInput): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.addMessageLog(to_candid_MessageLogInput_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMessageLog(to_candid_MessageLogInput_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async connectClient(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.connectClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.connectClient(arg0);
            return result;
        }
    }
    async createCampaign(arg0: CampaignRequest): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.createCampaign(to_candid_CampaignRequest_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCampaign(to_candid_CampaignRequest_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createContactList(arg0: string, arg1: string): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.createContactList(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createContactList(arg0, arg1);
            return result;
        }
    }
    async deleteCampaign(arg0: Id): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCampaign(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCampaign(arg0);
            return result;
        }
    }
    async deleteContact(arg0: Id): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContact(arg0);
            return result;
        }
    }
    async deleteContactList(arg0: Id): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContactList(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContactList(arg0);
            return result;
        }
    }
    async disconnectClient(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.disconnectClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.disconnectClient(arg0);
            return result;
        }
    }
    async extractGroupContacts(arg0: string, arg1: string): Promise<Array<GroupContact>> {
        if (this.processError) {
            try {
                const result = await this.actor.extractGroupContacts(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.extractGroupContacts(arg0, arg1);
            return result;
        }
    }
    async getCampaigns(): Promise<Array<Campaign>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCampaigns();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCampaigns();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClientStatuses(): Promise<Array<ClientStatus>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClientStatuses();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClientStatuses();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactLists(): Promise<Array<ContactList>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactLists();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactLists();
            return result;
        }
    }
    async getContactsInList(arg0: Id): Promise<Array<Contact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactsInList(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactsInList(arg0);
            return result;
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getMessageLogs(arg0: MessageFilter): Promise<Array<MessageLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessageLogs(to_candid_MessageFilter_n21(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessageLogs(to_candid_MessageFilter_n21(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async importContacts(arg0: Id, arg1: Array<ContactInput>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.importContacts(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importContacts(arg0, arg1);
            return result;
        }
    }
    async pauseCampaign(arg0: Id): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.pauseCampaign(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pauseCampaign(arg0);
            return result;
        }
    }
    async saveGroupContactsToList(arg0: Id, arg1: Array<ContactInput>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveGroupContactsToList(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveGroupContactsToList(arg0, arg1);
            return result;
        }
    }
    async startCampaign(arg0: Id): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.startCampaign(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startCampaign(arg0);
            return result;
        }
    }
    async updateClientStatus(arg0: string, arg1: boolean, arg2: string | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClientStatus(arg0, arg1, to_candid_opt_n28(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClientStatus(arg0, arg1, to_candid_opt_n28(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_CampaignStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CampaignStatus): CampaignStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Campaign_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Campaign): Campaign {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_ClientStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClientStatus): ClientStatus {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_MessageLog_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageLog): MessageLog {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_MessageStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageStatus): MessageStatus {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_MessageType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageType): MessageType {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    status: _CampaignStatus;
    startedAt: [] | [_Timestamp];
    delaySecs: bigint;
    name: string;
    createdAt: _Timestamp;
    totalCount: bigint;
    sentCount: bigint;
    messageType: _MessageType;
    message: string;
    mediaPath: [] | [string];
    clientIds: Array<string>;
    listId: _Id;
    scheduledAt: [] | [_Timestamp];
}): {
    id: Id;
    status: CampaignStatus;
    startedAt?: Timestamp;
    delaySecs: bigint;
    name: string;
    createdAt: Timestamp;
    totalCount: bigint;
    sentCount: bigint;
    messageType: MessageType;
    message: string;
    mediaPath?: string;
    clientIds: Array<string>;
    listId: Id;
    scheduledAt?: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_CampaignStatus_n12(_uploadFile, _downloadFile, value.status),
        startedAt: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.startedAt)),
        delaySecs: value.delaySecs,
        name: value.name,
        createdAt: value.createdAt,
        totalCount: value.totalCount,
        sentCount: value.sentCount,
        messageType: from_candid_MessageType_n15(_uploadFile, _downloadFile, value.messageType),
        message: value.message,
        mediaPath: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.mediaPath)),
        clientIds: value.clientIds,
        listId: value.listId,
        scheduledAt: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.scheduledAt))
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    clientId: string;
    lastSeenAt: [] | [_Timestamp];
    name: string;
    connected: boolean;
    phone: [] | [string];
}): {
    clientId: string;
    lastSeenAt?: Timestamp;
    name: string;
    connected: boolean;
    phone?: string;
} {
    return {
        clientId: value.clientId,
        lastSeenAt: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.lastSeenAt)),
        name: value.name,
        connected: value.connected,
        phone: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    status: _MessageStatus;
    messagePreview: string;
    campaignId: _Id;
    sentAt: _Timestamp;
    error: [] | [string];
    contactId: _Id;
    phone: string;
}): {
    id: Id;
    status: MessageStatus;
    messagePreview: string;
    campaignId: Id;
    sentAt: Timestamp;
    error?: string;
    contactId: Id;
    phone: string;
} {
    return {
        id: value.id,
        status: from_candid_MessageStatus_n26(_uploadFile, _downloadFile, value.status),
        messagePreview: value.messagePreview,
        campaignId: value.campaignId,
        sentAt: value.sentAt,
        error: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.error)),
        contactId: value.contactId,
        phone: value.phone
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    running: null;
} | {
    paused: null;
}): CampaignStatus {
    return "pending" in value ? CampaignStatus.pending : "completed" in value ? CampaignStatus.completed : "running" in value ? CampaignStatus.running : "paused" in value ? CampaignStatus.paused : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    imageText: null;
} | {
    text: null;
} | {
    videoText: null;
} | {
    document: null;
}): MessageType {
    return "imageText" in value ? MessageType.imageText : "text" in value ? MessageType.text : "videoText" in value ? MessageType.videoText : "document" in value ? MessageType.document : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sent: null;
} | {
    failed: null;
}): MessageStatus {
    return "sent" in value ? MessageStatus.sent : "failed" in value ? MessageStatus.failed : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ClientStatus>): Array<ClientStatus> {
    return value.map((x)=>from_candid_ClientStatus_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MessageLog>): Array<MessageLog> {
    return value.map((x)=>from_candid_MessageLog_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Campaign>): Array<Campaign> {
    return value.map((x)=>from_candid_Campaign_n10(_uploadFile, _downloadFile, x));
}
function to_candid_CampaignRequest_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CampaignRequest): _CampaignRequest {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_MessageFilter_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageFilter): _MessageFilter {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_MessageLogInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageLogInput): _MessageLogInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_MessageStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageStatus): _MessageStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_MessageType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageType): _MessageType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: MessageStatus;
    messagePreview: string;
    campaignId: Id;
    error?: string;
    contactId: Id;
    phone: string;
}): {
    status: _MessageStatus;
    messagePreview: string;
    campaignId: _Id;
    error: [] | [string];
    contactId: _Id;
    phone: string;
} {
    return {
        status: to_candid_MessageStatus_n3(_uploadFile, _downloadFile, value.status),
        messagePreview: value.messagePreview,
        campaignId: value.campaignId,
        error: value.error ? candid_some(value.error) : candid_none(),
        contactId: value.contactId,
        phone: value.phone
    };
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: MessageStatus;
    campaignId?: Id;
    toTime?: Timestamp;
    fromTime?: Timestamp;
}): {
    status: [] | [_MessageStatus];
    campaignId: [] | [_Id];
    toTime: [] | [_Timestamp];
    fromTime: [] | [_Timestamp];
} {
    return {
        status: value.status ? candid_some(to_candid_MessageStatus_n3(_uploadFile, _downloadFile, value.status)) : candid_none(),
        campaignId: value.campaignId ? candid_some(value.campaignId) : candid_none(),
        toTime: value.toTime ? candid_some(value.toTime) : candid_none(),
        fromTime: value.fromTime ? candid_some(value.fromTime) : candid_none()
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    delaySecs: bigint;
    name: string;
    messageType: MessageType;
    message: string;
    mediaPath?: string;
    clientIds: Array<string>;
    listId: Id;
    scheduledAt?: Timestamp;
}): {
    delaySecs: bigint;
    name: string;
    messageType: _MessageType;
    message: string;
    mediaPath: [] | [string];
    clientIds: Array<string>;
    listId: _Id;
    scheduledAt: [] | [_Timestamp];
} {
    return {
        delaySecs: value.delaySecs,
        name: value.name,
        messageType: to_candid_MessageType_n7(_uploadFile, _downloadFile, value.messageType),
        message: value.message,
        mediaPath: value.mediaPath ? candid_some(value.mediaPath) : candid_none(),
        clientIds: value.clientIds,
        listId: value.listId,
        scheduledAt: value.scheduledAt ? candid_some(value.scheduledAt) : candid_none()
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageStatus): {
    sent: null;
} | {
    failed: null;
} {
    return value == MessageStatus.sent ? {
        sent: null
    } : value == MessageStatus.failed ? {
        failed: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageType): {
    imageText: null;
} | {
    text: null;
} | {
    videoText: null;
} | {
    document: null;
} {
    return value == MessageType.imageText ? {
        imageText: null
    } : value == MessageType.text ? {
        text: null
    } : value == MessageType.videoText ? {
        videoText: null
    } : value == MessageType.document ? {
        document_: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
